<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends EntityRepository
{
    public function findCarsByMake(string $make){
        $query = $this->createQueryBuilder('car')
            ->select('car')
            ->from('AppBundle:Car', 'c')
            ->where("car.make = :make")
            ->setParameter(':make',$make)
            ->addOrderBy('car.model', 'ASC')
            ->addOrderBy('car.travelledDistance','DESC')
            ->getQuery();

        return $query->getResult();
    }

    /**
     * @param int $id
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findCarWithParts(int $id){
        return $this->createQueryBuilder('car')
            ->select('car')
            ->from('AppBundle:Car','c')
            ->leftJoin('car.parts','parts')
            ->where('car.id = :id')
            ->setParameter(':id',$id)
            ->getQuery()
            ->getSingleResult();
    }

}
