<?php

namespace AppBundle\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCustomersByBirthDate(string $order)
    {
        $query = $this->createQueryBuilder('customer')
            ->select('customer')
            ->from('AppBundle:Customer', 'c')
            ->addOrderBy('customer.birthDate', $order)
            ->addOrderBy('customer.isYoungDriver','ASC')
            ->getQuery();

        return $query->getResult();

//        $query = $this
//            ->getEntityManager()
//            ->createQuery("SELECT customer
//                               FROM AppBundle:Customer AS customer
//                               ORDER BY customer.birthDate ASC")
//        $result=$query->getResult();

    }

    /**
     * @param int $id
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findCustomerSales(int $id)
    {
        return  $this->createQueryBuilder('customer')
            ->select('customer')
            ->from('AppBundle:Customer', 'c')
            ->where('customer.id = :id')
            ->setParameter(':id',$id)
            ->getQuery()
            ->getSingleResult();
    }
}
