<?php

namespace SoftUniBlogBundle\Repository;
use SoftUniBlogBundle\Entity\Article;
use SoftUniBlogBundle\Entity\Comment;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
