<?php

namespace SoftUniBlogBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    const LIMIT=5;

    public function findCommentsByArticleSort($id){
        $query= $this
            ->getEntityManager()
            ->createQueryBuilder()
            ->select('comments')
            ->from('SoftUniBlogBundle:Comment','comments')
            ->where('comments.article = :id')
            ->orderBy('comments.dateAdded', 'DESC')
            ->setParameter(':id',$id)
            ->getQuery()
//            ->setFirstResult(2)
            ->setMaxResults(self::LIMIT);

        return $query->getResult();
    }
}
