<?php

namespace SoftUniBlogBundle\Repository;
/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    const MESSAGE_STATE = '0';

    public function findByRecipient(int $id){
        $query=$this
            ->createQueryBuilder('message')
            ->select('message')
            ->from('SoftUniBlogBundle:Message','m')
            ->where("message.recipient = :id")
            ->andWhere("message.isRead = :state")
            ->setParameter(':id',$id)
            ->setParameter(':state', self::MESSAGE_STATE)
            ->getQuery();

        return $query->getResult();
    }
}
