<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new Mapping\ClassMetadata(User::class));
    }

    /**
     * @param int $length
     * @return User[]|array
     */
    public function findByUsernameLength(int $length):array{
        $query = $this->_em->createQueryBuilder()
            ->select('user')
            ->from("AppBundle:User",'user')
            ->where('LENGTH(user.username) = :len')
            ->setParameter(':len',$length)
            ->getQuery();

        return $query->getResult();
    }

    public function save(User $user){
        $this->_em->persist($user);
        $this->_em->flush();
    }
}
